
---
- hosts: web_server
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: ping um
    ping:

  - name: install JRE
    apt:
      update_cache: yes
      name: openjdk-8-jre-headless

  - name: install nginx
    apt:
      update_cache: yes
      name: nginx

  - name: stop nginx
    service:
      name: nginx
      state: stopped

  - name: copy public certificate
    copy:
      src: artifacts/bytes.crt
      dest: /etc/ssl/certs/bytes.crt
      owner: root
      group: root
      mode: u+rw,g+r,o+r

  - name: copy private certificate
    copy:
      src: artifacts/secure/bytes.key
      dest: /etc/ssl/private/bytes.key
      owner: root
      group: root
      mode: u+rw,g-rwx,o-rwx

  - name: copy nginx config
    copy:
      src: artifacts/nginx-default-site
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: u+rw-x,g+r-wx,o+r-wx
      
  - name: ensure nginx running
    service:
      name: nginx
      state: started

  - name: create daily app user account
    user:
      name: daily-app
      state: present
      system: yes
      shell: /bin/false
      createhome: no

  - name: Create a directory if it does not exist
    file:
      path: /usr/local/daily-goal-app
      state: directory
      owner: daily-app
      group: daily-app
      mode: '0755'
    
  - name: copy daily app jar
    copy:
      src: daily-goal-app/target/daily-goal-app-0.1.0-SNAPSHOT-standalone.jar
      dest: /usr/local/daily-goal-app/daily-goal-app.jar
      owner: daily-app
      group: daily-app
      mode: u+rx-w,g+rx-w,o+rx-w

  - name: copy daily app service file
    copy:
      src: artifacts/daily-goal-app.service
      dest: /etc/systemd/system/daily-goal-app.service
      owner: root
      group: root
      mode: u+rw-x,g+r-wx,o+r-wx

  - name: start daily app service
    systemd:
      state: started
      name: daily-goal-app
